-- Intentionally empty: Supabase seeds before separate Drizzle migrations run.
-- The Drizzle P0 migration inserts minimal settings and section defaults.
-- Seed configuration reference: supabase/config.toml [db.seed].
-- Never seed Auth users, credentials, production data, or provider secrets.
