import "server-only";

import { parseServerEnv } from "./server-schema";

export const serverEnv = parseServerEnv({
  NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_META_PIXEL_ID: process.env.NEXT_PUBLIC_META_PIXEL_ID,
  NEXT_PUBLIC_GTM_CONTAINER_ID: process.env.NEXT_PUBLIC_GTM_CONTAINER_ID,
  DATABASE_URL: process.env.DATABASE_URL,
  SUPABASE_SECRET_KEY: process.env.SUPABASE_SECRET_KEY,
  SUPABASE_PUBLIC_ASSET_BUCKET: process.env.SUPABASE_PUBLIC_ASSET_BUCKET,
  META_CAPI_DATASET_ID: process.env.META_CAPI_DATASET_ID,
  META_CAPI_ACCESS_TOKEN: process.env.META_CAPI_ACCESS_TOKEN,
  META_AD_ACCOUNT_ID: process.env.META_AD_ACCOUNT_ID,
  META_MARKETING_API_ACCESS_TOKEN: process.env.META_MARKETING_API_ACCESS_TOKEN,
  GA4_PROPERTY_ID: process.env.GA4_PROPERTY_ID,
  GA4_SERVICE_ACCOUNT_EMAIL: process.env.GA4_SERVICE_ACCOUNT_EMAIL,
  GA4_SERVICE_ACCOUNT_PRIVATE_KEY: process.env.GA4_SERVICE_ACCOUNT_PRIVATE_KEY,
  FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY,
  TRACKING_ENABLED: process.env.TRACKING_ENABLED,
  CRON_SECRET: process.env.CRON_SECRET,
});
